# DigitalOcean App Platform Configuration
# Deploy Redactor AI with interactive text selection

name: redactor-ai
region: fra # Frankfurt (closest to Italy)

# Frontend: React App (from desktop build)
services:
  - name: frontend
    github:
      repo: stefanoallima/codicecivileai
      branch: main
      deploy_on_push: true

    source_dir: /desktop

    build_command: |
      npm install
      npm run build:renderer

    run_command: npx serve -s dist/renderer -l 8080

    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month

    envs:
      - key: NODE_ENV
        value: production

    http_port: 8080

    routes:
      - path: /

  # Backend: Python FastAPI
  - name: backend
    github:
      repo: stefanoallima/codicecivileai
      branch: main
      deploy_on_push: true

    source_dir: /desktop/src/python

    build_command: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_lg

    run_command: uvicorn main:app --host 0.0.0.0 --port 8080

    instance_count: 1
    instance_size_slug: basic-xs  # $5/month (need more RAM for AI models)

    envs:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SHARED_BACKEND_PATH
        value: /workspace/shared_backend

    http_port: 8080

    routes:
      - path: /api

# Total cost: ~$10/month (prorate to ~€2-3 for a few days)
